import sys
import os
import subprocess
import argparse
from pathlib import Path

# Try to import mlx_whisper. If it's missing, provide a clear error trace for the Agent.
try:
    import mlx_whisper
except ImportError:
    print("[ERROR] mlx_whisper is not installed. Please run: pip install mlx-whisper yt-dlp")
    sys.exit(1)

def extract_audio(url, output_dir):
    """
    Downloads ONLY the audio track from the given URL using yt-dlp.
    Returns the path to the extracted audio file.
    """
    print(f"[INFO] 正在调用 yt-dlp 剥离流媒体纯音频: {url} ...")
    
    # We download as .m4a because it's fast and natively supported.
    # --force-overwrites ensures we don't halt on prompt
    outtmpl = os.path.join(output_dir, "extracted_audio.%(ext)s")
    
    cmd = [
        "yt-dlp",
        "-x",  # Extract audio
        "--audio-format", "m4a",
        "--force-overwrites",
        "-o", outtmpl,
        url
    ]
    
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] yt-dlp 下载失败. 可能是受到强反爬或链接无效.\n{e.stderr.decode()}")
        sys.exit(1)
        
    expected_file = os.path.join(output_dir, "extracted_audio.m4a")
    if not os.path.exists(expected_file):
        print(f"[ERROR] 音频文件剥离流未能成功定位到 {expected_file}")
        sys.exit(1)
        
    return expected_file

def transcribe_audio(audio_path, output_md_path):
    """
    Uses MLX-Whisper to transcribe the audio file on local Apple Silicon.
    No slicing needed for M4 Pro!
    """
    print(f"[INFO] 捕获纯净音频，开始交由 M4 Pro MLX 神经核进行零时差听写转录...")
    
    try:
        # Utilizing mlx-whisper large-v3 for maximum accuracy.
        # path_or_hf_repo defaults to "mlx-community/whisper-large-v3-mlx".
        text = mlx_whisper.transcribe(
            audio_path,
            path_or_hf_repo="mlx-community/whisper-large-v3-mlx",
            fp16=True 
        )["text"]
    except Exception as e:
        print(f"[ERROR] 神经核听写失败: {str(e)}")
        sys.exit(1)
        
    # Formatting output for Markdown
    content = f"# Media Extraction Transcript\n\n**Source Audio**: {audio_path}\n**Generated By**: MLX-Whisper on Apple Silicon\n\n---\n\n{text}\n"
    
    with open(output_md_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"\n[SUCCESS] 万字剥离听写已全自动完成！")
    print(f"[RESULT_FILE_PATH] {output_md_path}")
    return output_md_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Media Extractor using yt-dlp and MLX-Whisper")
    parser.add_argument("url", help="目标在线流媒体视频或音频URL (如 抖音/YouTube 链接)")
    args = parser.parse_args()

    # 工作空间设定 (存放在 ~ / .openclaw / media/)
    base_dir = os.path.expanduser("~/.openclaw/media/extractor_temp")
    os.makedirs(base_dir, exist_ok=True)
    
    output_md_path = os.path.join(base_dir, "final_transcript.md")
    
    # 步骤 1：全自动音频降维下载
    audio_file = extract_audio(args.url, base_dir)
    
    # 步骤 2：基于 M 系列芯片的快速离线解密
    result_path = transcribe_audio(audio_file, output_md_path)
    
    # 步骤 3：清理巨大音频残骸以防挤爆硬盘
    try:
         os.remove(audio_file)
         print(f"[INFO] 临时音频文件已清理脱落...")
    except Exception:
         pass
         
    # 结果供外部 Agent 拿取
    print("\n==== 给 Agent 的指示 ====")
    print(f"提取结果均已物理沉淀至上述 [RESULT_FILE_PATH] 中。请直接使用您的能力读取文件: {result_path}，然后进行进一步的结构化分析与入库。")
