import sys
import os
import subprocess
import argparse
import re
from pathlib import Path

# Try to import mlx_whisper. If it's missing, provide a clear error trace for the Agent.
try:
    import mlx_whisper
except ImportError:
    print("[ERROR] mlx_whisper is not installed. Please run: pip3 install mlx-whisper yt-dlp")
    print("[提示] 并在运行时使用 `python3` 代替 `python`！")
    sys.exit(1)

def extract_url_from_text(text):
    """
    如果用户塞进来的是一大片口令（例如抖音的分享文案），强制用正则把 http 链接抠出来。
    """
    match = re.search(r'(https?://[^\s]+)', text)
    if match:
        return match.group(1)
    return text

def extract_audio(url, output_dir):
    """
    Downloads ONLY the audio track from the given URL using yt-dlp.
    Returns the path to the extracted audio file.
    """
    print(f"[INFO] 正在调用 yt-dlp 剥离流媒体纯音频: {url} ...")
    
    outtmpl = os.path.join(output_dir, "extracted_audio.%(ext)s")
    base_cmd = [
        "yt-dlp",
        "-x",  # Extract audio
        "--audio-format", "m4a",
        "--force-overwrites",
        "-o", outtmpl
    ]

    # 为了应对反爬（尤其是抖音/TikTok要求新鲜Cookie），设定一组穿透策略
    strategies = [
        [],  # 策略1：先尝试不带 Cookie 硬穿
        ["--cookies-from-browser", "safari"],  # 策略2：借用 Mac 自带 Safari
        ["--cookies-from-browser", "chrome"],  # 策略3：借用 Chrome
        ["--cookies-from-browser", "edge"]     # 策略4：借用 Edge
    ]

    success = False
    for strategy in strategies:
        cmd = base_cmd + strategy + [url]
        msg_suffix = " (无Cookie)" if not strategy else f" (借助 {strategy[1]} Cookie 渗透)"
        print(f"[INFO] 尝试穿透反爬网关{msg_suffix}...")
        
        try:
            # 捕获输出以避免满屏幕刷红报错
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode == 0:
                success = True
                break
        except Exception:
            continue

    if not success:
        print(f"[ERROR] 所有的反爬穿透策略均已失效. 可能需要手动从浏览器导出 cookies.txt 给 yt-dlp。")
        sys.exit(1)
        
    expected_file = os.path.join(output_dir, "extracted_audio.m4a")
    if not os.path.exists(expected_file):
        print(f"[ERROR] 音频文件剥离流未能成功定位到 {expected_file}")
        sys.exit(1)
        
    return expected_file

def transcribe_audio(audio_path, output_md_path):
    """
    Uses MLX-Whisper to transcribe the audio file on local Apple Silicon.
    No slicing needed for M4 Pro!
    """
    print(f"[INFO] 捕获纯净音频，开始交由 M4 Pro MLX 神经核进行零时差听写转录...")
    
    try:
        # Utilizing mlx-whisper large-v3 for maximum accuracy.
        # path_or_hf_repo defaults to "mlx-community/whisper-large-v3-mlx".
        text = mlx_whisper.transcribe(
            audio_path,
            path_or_hf_repo="mlx-community/whisper-large-v3-mlx",
            fp16=True 
        )["text"]
    except Exception as e:
        print(f"[ERROR] 神经核听写失败: {str(e)}")
        sys.exit(1)
        
    # Formatting output for Markdown
    content = f"# Media Extraction Transcript\n\n**Source Audio**: {audio_path}\n**Generated By**: MLX-Whisper on Apple Silicon\n\n---\n\n{text}\n"
    
    with open(output_md_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"\n[SUCCESS] 万字剥离听写已全自动完成！")
    print(f"[RESULT_FILE_PATH] {output_md_path}")
    return output_md_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Media Extractor using yt-dlp and MLX-Whisper")
    parser.add_argument("url", help="目标在线流媒体视频或音频URL (如 抖音/YouTube 链接)")
    args = parser.parse_args()

    # 工作空间设定 (存放在 ~ / .openclaw / media/)
    base_dir = os.path.expanduser("~/.openclaw/media/extractor_temp")
    os.makedirs(base_dir, exist_ok=True)
    
    output_md_path = os.path.join(base_dir, "final_transcript.md")
    
    # 步骤 1：全自动音频降维下载
    clean_url = extract_url_from_text(args.url)
    audio_file = extract_audio(clean_url, base_dir)
    
    # 步骤 2：基于 M 系列芯片的快速离线解密
    result_path = transcribe_audio(audio_file, output_md_path)
    
    # 步骤 3：清理巨大音频残骸以防挤爆硬盘
    try:
         os.remove(audio_file)
         print(f"[INFO] 临时音频文件已清理脱落...")
    except Exception:
         pass
         
    # 结果供外部 Agent 拿取
    print("\n==== 给 Agent 的指示 ====")
    print(f"提取结果均已物理沉淀至上述 [RESULT_FILE_PATH] 中。请直接使用您的能力读取文件: {result_path}，然后进行进一步的结构化分析与入库。")
